### PR TITLE
Docs: Quay Builders support with custom signed CA

### PR DESCRIPTION
**Pull request by alekssaul**
Add example of builders support for connecting Quay Enterprise signed by custom CA

Tested as below:
image

### CODE REVIEW

**Comment by joshix** [comment]
@alekssaul I think this LGTM, if you think the tweaks I made are reasonable. Let me know and we can merge.

**Comment by joshix** [comment]
ref https://github.com/coreos-inc/quay-builder/issues/76

**Comment by alekssaul** [comment]
LGTM.  ping @josephschorr to make sure there hasn't been any changes to cert store or startup scripts between 2.0.1 and 2.1.0

**Comment by josephschorr** [comment]
No changes

**Comment by joshix** [comment]
sorry that languished, @alekssaul  -- merged now and closed https://github.com/coreos-inc/quay-builder/issues/76 along with it. Thanks for writing it up.

**Pull request merged**
