### PR TITLE
mantle: add documentation for mantle

### PR DESCRIPTION
**Pull request by pbx0**

### CODE REVIEW

**Comment by marineam** [comment]
Could use some links to it :)

**Comment by robszumski** [comment]
Content and everything LGTM

**Comment by pbx0** [comment]
@marineam Links to the repository?

**Comment by marineam** [comment]
links from other docs to here so it is discoverable

**Comment by pbx0** [comment]
Added a link at the bottom of the main SDK doc, modifying-coreos.

**Comment by marineam** [comment]
LGTM

**Pull request merged**
