### PR TITLE
iPXE supports HTTPS.

### PR DESCRIPTION
**Pull request by Manouchehri**

### CODE REVIEW

**Comment by joshix** [comment]
@Manouchehri Thanks for the suggestion! We're exploring the addition of this build opt to the ipxe shipped in CoreOS in the future. In the meantime, however, I don't want to instruct users to rebuild ipxe, so I'm closing this PR in favor of coreos/bugs#1044

**Comment by Manouchehri** [comment]
@joshix I've removed my suggest about using a custom iPXE build, should be fine to merge now.

**Comment by joshix** [comment]
@Manouchehri  Improved the doc. Thank you.

(TODO: bring this doc more in line with the [(WIP) style guide](https://github.com/joshix/docs/blob/styledir-hdings/STYLE.md).

**Comment by joshix** [comment]
related coreos/bugs#1034

**Pull request merged**
