### PR TITLE
Run commands on a fleet host vs Kubernetes inital

### PR DESCRIPTION
**Pull request by ElijahCaine**
This is a work in progress. Feedback and discussion encouraged.

References documentation needed to transition toward Kubernetes from fleet.

cc: @joshix

### CODE REVIEW

**Comment by philips** [comment]
Kubernetes has an ExternalIP field. We can use this.

```
$ kubectl get nodes -o json ip-10-0-0-50.us-west-2.compute.internal | jq .status.addresses
[
  {
    "address": "10.0.0.50",
    "type": "InternalIP"
  },
  {
    "address": "10.0.0.50",
    "type": "LegacyHostIP"
  },
  {
    "address": "52.26.54.211",
    "type": "ExternalIP"
  },
  {
    "address": "ip-10-0-0-50",
    "type": "Hostname"
  }
]
```

**Comment by philips** [comment]
```
ssh $(kubectl get nodes -o template ip-10-0-0-50.us-west-2.compute.internal --template='{{range .status.addresses}}{{if eq .type "ExternalIP"}}{{.address}}{{end}}{{end}}') -l core
```

**Comment by zbwright** [comment]
fleet is no longer developed or maintained by CoreOS. And we've redesigned the entire kubernetes section. @joshix take a look, please, and let me know if you think we should keep this PR open. we might be able to re-use some of the content elsewhere.

**Comment by joshix** [comment]
superseded and/or incorporated in later content

**Pull request closed without merging**
