### PR TITLE
Added system wide env vars example

### PR DESCRIPTION
**Pull request by kayrus**
/cc @joshix @robszumski

### CODE REVIEW

**Comment by robszumski** [comment]
This is great, I was just thinking that we needed to document this earlier today.

**Comment by kayrus** [comment]
use `libastral.so.5`, @robszumski ;)

**Comment by crawford** [comment]
Can you also provide an Ignition config?

**Comment by kayrus** [comment]
@crawford done

**Comment by crawford** [comment]
LGTM

**Pull request merged**
