### PR TITLE
Added SElinux support for libvirt script

### PR DESCRIPTION
**Pull request by kayrus**
Removed odd whitespaces and added some logic for the future

fixes https://github.com/coreos/bugs/issues/1077

/cc @joshix @robszumski

### CODE REVIEW

**Comment by joshix** [comment]
LGTM, have only brain-tested (not executed)

**Comment by joshix** [comment]
https://github.com/coreos/bugs/issues/1077#issuecomment-183010781

(ie, there is more to this than, "will this script bail with a syntax error?")

**Comment by kayrus** [comment]
It works at least in debian/ubuntu and fedora.

**Comment by ElijahCaine** [comment]
@kayrus In an effort to clean up some old PRs I'd like to know if you've got any changes you'd like to make to this and if you're able to resolve the conflicts.

If you don't think this change still needs to be made we can close this PR.

**Comment by kayrus** [comment]
I don't think it is necessary to keep these scripts inside coreos docs repo. I work on them in my private repo. Most probably it's worth to post a link to them or completely remove. https://github.com/kayrus/deploy-vm

**Comment by joshix** [comment]
Closed inactive per originator

**Pull request closed without merging**
