### PR TITLE
ignition/examples: Tweaks to language and format.

### PR DESCRIPTION
**Pull request by joshix**
Unwrap lines. Inline links. ATX headers. Typos fixed. Polish a little language. Ref #633

### CODE REVIEW

**Comment by crawford** [comment]
-1

**Comment by joshix** [comment]
@crawford On the unwrap?

**Comment by crawford** [comment]
Yeah. Everything else looks good.

**Comment by joshix** [comment]
Gotcha. I think the churn wrapping causes in prose is just too troublesome. So we're going to have long markdown lines if it's my call. 

I do however understand where you're coming from. In the spirit of gofmt, I think we can all benefit from picking a format even tho that format may not entirely please any one individual. 

I humbly submit that its pretty easy to read these in a terminal with fmt.

**Comment by crawford** [comment]
Died a little inside. Thanks for not going full-retard and doing one sentence per line.

**Comment by joshix** [comment]
I couldn't find my special hat for that.

**Pull request merged**
