### PR TITLE
etcd/: Update 10 rel links to crawfred style

### PR DESCRIPTION
**Pull request by joshix**
Match downstream backport prequel coreos-inc/coreos-pages#639

### CODE REVIEW

**Comment by crawford** [comment]
This is not correct. All links within this repo need to resolve. Please revert.

**Comment by joshix** [comment]
When do we do the rewrite?

**Comment by crawford** [comment]
The import script handles all rewrites.

**Comment by joshix** [comment]
It didn't handle these -- I did them by hand in coreos-inc/coreos-pages#639

**Comment by crawford** [comment]
We need to fix the script then.

**Comment by joshix** [comment]
I squashed that commit away, but I had to go through and replace `../os/` with `../../../os/docs/latest/` throughout _etcd/2.3.2/ and _etcd/latest/ -- *in the etcd docs that live in coreos/docs/etcd/*

**Pull request merged**
