### PR TITLE
running-coreos: add niftycloud docs

### PR DESCRIPTION
**Pull request by higebu**
Add English and Japanese version of NIFTY Cloud docs.

### CODE REVIEW

**Comment by sym3tri** [comment]
日本語 LGTM

**Comment by higebu** [comment]
Thank you for merging!
How to become an official platform?

**Comment by robszumski** [comment]
@higebu Official platforms are ones where we work with the provider to make sure CoreOS will continue to work well, integrate into our testing process and generally meet the quality and experience guidelines that we want for our customers. Each official platform we add means more work for us, so we don't take it lightly.

There are some business requirements to being listed there as well, but if you're interested in starting the conversation you can reach out to partners@coreos.com to get started.

**Comment by higebu** [comment]
@robszumski Thank you for your reply. We'll consider it.

**Pull request merged**
