### PR TITLE
Convert ext4 to btrfs during installation

### PR DESCRIPTION
**Pull request by LuizOz**
Please, merge if you guys find that useful, thanks.

### CODE REVIEW

**Comment by jumanjiman** [comment]
:+1: to merge this. useful tip!

**Comment by crawford** [comment]
This can be done in a more general manner with [Ignition](https://coreos.com/ignition/docs/latest/examples.html#reformat-the-root-filesystem).

**Comment by joshix** [comment]
Closed in favor of Ignition method: https://coreos.com/ignition/docs/latest/examples.html#reformat-the-root-filesystem

**Comment by crawford** [comment]
Atta boy.

**Pull request closed without merging**
