### PR TITLE
quay-enterprise/: Update quay container version to current 1.16.3

### PR DESCRIPTION
**Pull request by joshix**
Ref https://github.com/coreos-inc/tectonic-pages/pull/211

Proposed TODO: These should be version "latest", as they are in the
quay-enterprise yaml owned by the tectonic team, see
https://github.com/coreos-inc/tectonic/commit/4f15f8c58321ddf433ceb6ba3838875db2735353#diff-98914fd9e6d06eab312a20550c5fe2df

### CODE REVIEW

**Comment by joshix** [comment]
@Quentin-M What was the reasoning behind the change from `latest` to the specific versions in coreos-inc/tectonic-pages#187?

at any rate, "we must update these at release points..." :)

https://github.com/coreos-inc/tectonic-pages/pull/187#issuecomment-224722604

**Comment by joshix** [comment]
https://github.com/coreos-inc/tectonic-pages/issues/186 proposed adding the specific versions

**Comment by robszumski** [comment]
LGTM

**Comment by Quentin-M** [comment]
It was required at least for clair-jwt as the container is built using two different git repositories, both using the `master` branch by default, which is the development branch. The branch had breaking configuration changes and it was also quite confusing to use `latest` (which repository?).

**Pull request merged**
