### PR TITLE
Removed long ssh-rsa keys, updated iPXE and PXE docs, fixed links to …

### PR DESCRIPTION
**Pull request by kayrus**
…"config_drive" docs

/cc @brianredbeard
/cc @robszumski

### CODE REVIEW

**Comment by robszumski** [comment]
LGTM but I'd love to get more eyes on the iPXE stuff.

**Comment by marineam** [comment]
LGTM

**Comment by marineam** [comment]
actually, if we are dropping the rootfstype=btrfs in the doc we can drop the tmpfs one too since it doesn't make much sense without the alternative option.

**Comment by kayrus** [comment]
@robszumski specially for you I've added simple nginx config to host cloud-config files =)

**Comment by marineam** [comment]
@robszumski  I'm going to go ahead and merge, @ionave has related changes and want to avoid conflicts :)

**Pull request merged**
