### PR TITLE
golang: recommend glide instead of godep

### LINKED ISSUE #775: golang: migrate to Godep alternative?
We [currently recommend godep](https://github.com/coreos/docs/blame/master/golang/README.md#L48) as our standard solution for vendoring dependencies in CoreOS golang projects, but there are massive inconsistencies in how it's used (e.g. [using the vendor experiment](https://github.com/coreos/coreos-baremetal/tree/e43a018db3589f2909854b742e2346e698010466/vendor) or [not](https://github.com/coreos/rkt/tree/c9e393f7459a321c3c4303fdf2819e398d760845/Godeps/_workspace), [rewriting](https://github.com/coreos/etcd/blob/7879429a941ae5b57d6b8bc2bacffeae3ec73bc3/clientv3/auth.go#L18) or [not](https://github.com/coreos/rkt/blob/c9e393f7459a321c3c4303fdf2819e398d760845/scripts/godep-save#L30), using [scripts for management](https://github.com/coreos/rkt/blob/c9e393f7459a321c3c4303fdf2819e398d760845/scripts/godep-save)), and some projects [don't use it at all](https://github.com/coreos/ignition). And of course it provides a lot of difficulty for many developers trying to upgrade dependencies (not even going to bother to provide references for this point).

Given the number of developer hours we still lose to fiddling with Godep, and the general community sentiment towards it (e.g. projects like Kubernetes considering moving), it would be nice if we could agree on a sensible replacement with a more usable workflow, and recover a semblance of standardisation across CoreOS projects whereever possible.

The primary contender at the moment (ancedotally, see below) is [glide](https://github.com/Masterminds/glide).

Assorted non-exhaustive references:
coreos/rkt#1933
coreos/rkt#1424
coreos/coreos-baremetal#82
appc/acbuild#186
Masterminds/glide#303 (Kubernetes + others investigating migrating)

### PR DESCRIPTION
**Pull request by jonboulle**
fixes #775

### CODE REVIEW

**Comment by joshix** [comment]
LGTM as an excision of the existing and deprecated godep recommendation.

Will glide things like updating vendored deps require in-particular project guidance as they did with godep[1]? Or are the external docs fit for purpose there?

[1] https://github.com/coreos/docs/issues/775#issuecomment-207116463

**Comment by ericchiang** [comment]
I'll volunteer to write a "Using Glide" document based on my experience using it for a few projects (including Dex).

**Comment by jonboulle** [comment]
@s-urbaniak we can probably pull something from here?
https://github.com/coreos/rkt/blob/master/Documentation/hacking.md#managing-dependencies

**Comment by s-urbaniak** [comment]
@jonboulle Yes, the whole "Managing dependencies" chapter actually is not rkt-specific, except that we don't "like" declaring version ranges in `glide.yaml`, also https://github.com/coreos/rkt/blob/master/scripts/glide-update.sh turned out to be a good starting point for other projects.

**Comment by ElijahCaine** [comment]
@jonboulle this looks good to me.  The lack of a replacement for *Using Godep* seems like it might be a problem, but if the consensus is that we don't need a replacement doc this looks good to merge. 👍

**Pull request merged**
