### PR TITLE
[quay] add schema config for Quay Enterprise

### PR DESCRIPTION
**Pull request by IvanCherepov**
adds docs for schema

### CODE REVIEW

**Comment by zbwright** [comment]
I don't think this will work the way the Quay team wants it to work. The ask is that we publish an html document listing all Quay Enterprise schema. @crawford I'm pretty certain we cannot load individual style.css files into the sync process, and I don't know what it would do with a raw html file (schema.html). Do you have any suggestions for how this should be handled?

**Comment by crawford** [comment]
`sync` doesn't actually care about these files at all. It's Jekyll that processes them. Generally speaking though, I don't think we want rendered assets in this source repo.

**Comment by zbwright** [comment]
yeah - me neither. @IvanCherepov let's talk this out in slack.

**Comment by zbwright** [comment]
Ivan is going to see if he can't output to markdown instead.

**Comment by zbwright** [comment]
Use this (loosely) as an example: https://coreos.com/os/docs/latest/configuration.html
* Do the params need to be all caps?
* Make "Schema for Quay Enterprise" header1 (# Schema for Quay Enterprise)
* Make each param text, rather than bullet (AUTHENTICATION_TYPE [string] required)
* Bump nested lists out a level

(I think this will make it easier to read. The Container Linux example gets too complicated to follow. I think if each param were simply text, rather than bulleted text, it would add line breaks and formatting that makes it easier to follow.)

**Comment by zbwright** [comment]
let me know when this merges, and we'll get @athai to add it to the site. I think just drop in in under APIs under Reference on the landing page. Sound good, @josephschorr ?

**Comment by josephschorr** [comment]
@zbwright It should probably be under the setup section

**Comment by zbwright** [comment]
cool. thanks.

**Comment by josephschorr** [comment]
@IvanCherepov Please regenerate given recent schema changes

**Pull request merged**
