### PR TITLE
Correcting the ECS Agent systemd unit file.

### PR DESCRIPTION
**Pull request by JasonSwindle**

### CODE REVIEW

**Comment by bcwaldon** [comment]
@JasonSwindle Thanks for the PR! I'm not super familiar with the ECS agent, so please pardon my ignorance. What exactly justifies these changes?

**Comment by JasonSwindle** [comment]
Great question. This change makes sure that the new CloudWatch Metrics[1] get reported correctly. Also, the old version of the unit file was missing some flag / switches the ec-agent docs have.[2]  This will bring the ECS docs and the CoreOS example inline.


[1] http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html
[2] http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html

**Comment by JasonSwindle** [comment]
I see an error, let me fix it real fast. :)

**Comment by JasonSwindle** [comment]
Ok, there is the fix. Sorry about that error. :/

**Comment by JasonSwindle** [comment]
Going to re-do this PR, to make it overall cleaner. Sorry about that! :)

**Comment by JasonSwindle** [comment]
https://github.com/coreos/docs/pull/658

**Pull request closed without merging**
