### PR TITLE
os/env: remove spurious ExecStart

### PR DESCRIPTION
**Pull request by lucab**

### CODE REVIEW

**Comment by lucab** [comment]
/cc @crawford @robszumski 

I guess the empty property is a spurious line introduced in #999?

**Comment by crawford** [comment]
This is needed to clear the previous ExecStart, no?

**Comment by lucab** [comment]
I see. But then I'm confused about systemd.service doc which seems to allow this only for `Type=oneshot`.

**Comment by crawford** [comment]
Because `Type=oneshot` allows multiple `ExecStart`s, `ExecStart` has to be a list. Even though multiple `ExecStarts` aren't allowed in other service types, the directive's type is still the same. Just like other lists, an empty assignment will clear them.

**Comment by euank** [comment]
What @crawford's saying also matches my understanding.

**Comment by lucab** [comment]
Ack, sorry for the noise.

**Pull request closed without merging**
